version: '2'

services:

  ## --------------------------------------------------
  ## | proxy nginx
  ## --------------------------------------------------
  proxy:
    image: nginx:1.13.6-alpine
    expose:
     - "80"
     - "443"

    restart: unless-stopped
    volumes:
     - ./.docker-compose/proxy/sites/:/etc/nginx/sites-enabled/

  ## --------------------------------------------
  ## | wp1 web (php7 + apache 2.4)
  ## --------------------------------------------
  wp1_web:
    build:
      context: ./.docker-compose/web
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER_ID=${WWW_DATA_USER_ID}
    image: img_wp1_web
    expose:
      - "80"
      - "443"
    volumes:
      - ./src/wp1/:/var/www/html/
      - ./data/wp1_web/apache/logs/:/var/log/apache2
      - ./.docker-compose/wp1_web/apache.conf:/etc/apache2/sites-enabled/000-default.conf

    environment:
      - WORDPRESS_DB_HOST=behroo_wp_db
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}
    depends_on:
      - wp1_storage


  ## --------------------------------------------------
  ## | wp1 storage ( mysql 5.7.20 )
  ## --------------------------------------------------
  wp1_storage:
    image: mysql:5.7.20
    volumes:
      - ./data/db:/var/lib/mysql
      - ./.docker-compose/db/mysql/conf.d:/etc/mysql/conf.d/
    expose:
      - "3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${wp1_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${wp1_MYSQL_DATABASE}
      - MYSQL_USER=${wp1_MYSQL_USER}
      - MYSQL_PASSWORD=${wp1_MYSQL_PASSWORD}


  ## --------------------------------------------
  ## | wp2 web (php7 + apache 2.4)
  ## --------------------------------------------
  wp2_web:
    build:
      context: ./.docker-compose/web
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER_ID=${WWW_DATA_USER_ID}
    image: img_wp2_web
    expose:
      - "80"
      - "443"
    volumes:
      - ./src/wp2/:/var/www/html/
      - ./data/wp2_web/apache/logs/:/var/log/apache2
      - ./.docker-compose/wp2_web/apache.conf:/etc/apache2/sites-enabled/000-default.conf

    environment:
      - WORDPRESS_DB_HOST=wp2_storage
      - WORDPRESS_DB_NAME=${wp2_MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${wp2_MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${wp2_MYSQL_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${wp2_TABLE_PREFIX}
    depends_on:
      - wp2_storage



  ## --------------------------------------------------
  ## | wp1 storage ( mysql 5.7.20 )
  ## --------------------------------------------------
  wp2_storage:
    image: mysql:5.7.20
    volumes:
      - ./data/db:/var/lib/mysql
      - ./.docker-compose/db/mysql/conf.d:/etc/mysql/conf.d/
    expose:
      - "3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
